spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: work
    password: a7078796123A!
    url: jdbc:mysql://192.168.1.141:3306/sell?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
  cloud:
    stream:
      bindings:
        myMessage:
          group: order
          content-type: application/json
  redis:
    host: 192.168.1.141
    port: 6379
  rabbitmq:
      host: 192.168.1.141
      port: 5672
      username: guest
      password: guest
