spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: work
    password: a7078796123A!
    url: jdbc:mysql://192.168.1.141/sell?characterEncoding=utf-8&useSSL=false
  rabbitmq:
    host: 192.168.1.141
    port: 5672
    username: guest
    password: guest
  jpa:
    show-sql: true
